### ISSUE TITLE
Please clean up the project

### ISSUE THREAD

**Issue by vinjn** [GPUOpen-Tools/CxlCommon#2]
These files should never be commited.
*.sdf
*.ipch

**Comment by ilangal-amd** [comment]
Thanks for the notice. 
Files were cleaned in commits [28005c2](https://github.com/GPUOpen-Tools/CxlCommon/commit/28005c285048d917758c7db6d61040e31e061064), [8a2df6d](https://github.com/GPUOpen-Tools/CxlCommon/commit/8a2df6d0fc6a59957c33a74e964ab5ce7c4af814), [ca5374e](ca5374e76013523714c81b66cb05878abb241b3d) . 

Ilan.
